spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: miniretro
    driverClassName: org.postgresql.Driver
server:
  use-forward-headers: true
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://database:5432/postgres
